// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8u3WS4oYJ_uKjl-pejQHsdev2tFbRwYo',
    appId: '1:90283105369:web:dd067d2d0d85349842a548',
    messagingSenderId: '90283105369',
    projectId: 'mat-mat-app',
    authDomain: 'mat-mat-app.firebaseapp.com',
    storageBucket: 'mat-mat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFh39aijDbggRMjDhk2YqwClF-myqUUo',
    appId: '1:90283105369:android:270073b9f308254942a548',
    messagingSenderId: '90283105369',
    projectId: 'mat-mat-app',
    storageBucket: 'mat-mat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPnt33XP2LBnD0rgRfQCL7YfjstSTl_jY',
    appId: '1:90283105369:ios:4ffe9024ccb1390842a548',
    messagingSenderId: '90283105369',
    projectId: 'mat-mat-app',
    storageBucket: 'mat-mat-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPnt33XP2LBnD0rgRfQCL7YfjstSTl_jY',
    appId: '1:90283105369:ios:4ffe9024ccb1390842a548',
    messagingSenderId: '90283105369',
    projectId: 'mat-mat-app',
    storageBucket: 'mat-mat-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8u3WS4oYJ_uKjl-pejQHsdev2tFbRwYo',
    appId: '1:90283105369:web:e333d32cebd5be9542a548',
    messagingSenderId: '90283105369',
    projectId: 'mat-mat-app',
    authDomain: 'mat-mat-app.firebaseapp.com',
    storageBucket: 'mat-mat-app.firebasestorage.app',
  );
}
